### ISSUE TITLE
(Index) In Galaxy map, Left Grip does not make Left Stick control Z Axis

### ISSUE THREAD

**Issue by InsaneGrox** [boyestrous/elite-vr-cockpit#25]
Title basically, If right grip isn't held, left stick moves UI, if right grip is held, left stick moves X/Y Axis but not Z axis.

**Comment by boyestrous** [comment]
Sorry for the late reply. I have a fix for this and will upload in the next day or so... Just need to finalize and run tests.

**Comment by boyestrous** [comment]
This should be fixed with the [most recent release](https://github.com/boyestrous/elite-vr-cockpit/releases/tag/v0.9.41). 

You may have to go into the Steam VR Bindings Menu and make sure you're using the "official" one from this repo, but that _should_ happen automatically

**Comment by InsaneGrox** [comment]
https://github.com/boyestrous/elite-vr-cockpit/assets/54233743/c69fd892-8979-4902-b7d2-ce75bea1a1db

... I am so sorry for this but that fix not only didn't work, but it made things worse

**Comment by InsaneGrox** [comment]
disregard that last statement, had bindings ingame set wrong, galaxy map still doesnt let me z translate tho

**Comment by boyestrous** [comment]
Ah drat! I'm sorry you're still having issues. 

I think there's something missing when a new release comes out, it might not replace the Steam VR bindings as intended (those are separate from the in-game bindings). I'm working on a new screen for the desktop view that will highlight incorrect game bindings, but it's not done yet. 

**Could you post your .binds file and screenshot your SteamVR bindings?**
Examples below:

**Binds File**
Located in %Appdata%\Local\Frontier Developments\Elite Dangerous\Options\Bindings
Look for the file called **_Custom.4.0.binds_**

**SteamVR Bindings**
I need to see your bindings for the "fsscontrols" tab, like the below. Scroll down so the "Grip" is visible on both the left and right sides:
![image](https://github.com/boyestrous/elite-vr-cockpit/assets/13008046/bc5b62b4-fde8-4746-9742-6c9947d8f327)

**Comment by InsaneGrox** [comment]
The binds file was my own fault, I had my general binds set to keyboard+mouse instead of custom, however the steamVR bindings... 
![image](https://github.com/boyestrous/elite-vr-cockpit/assets/54233743/b7ac0030-691d-44b4-9243-b2a1a51145a6)

![image](https://github.com/boyestrous/elite-vr-cockpit/assets/54233743/0e188a78-59f5-4378-82ae-9999b4febd25)
yeeeah idk why that's not bound

**Comment by enzoescipy** [comment]
I am using the Oculus Quest 3 and have the same issue in Beta-0.9.41, which is I can't use any of map moving, pitching, tilting at all. So I checked the SteamVR bindings and I also found that fsscontrol tab's grip trigger option is completely missing. 

However, I could select the official binding for application and after appling that, I could move the map freely.

**Comment by boyestrous** [comment]
Closing this issue (which is solved by using the correct bindings from the most recent release). Opening #28 to track progress on the automatic future updates of SteamVR Bindings.
